Update claude-review.yml

diff --git a/.github/workflows/claude-review.yml b/.github/workflows/claude-review.yml
--- a/.github/workflows/claude-review.yml
+++ b/.github/workflows/claude-review.yml
@@ -35,8 +35,16 @@ jobs:
       - name: Total security issues
         run: |
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
-             echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
+             echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
 
+      - name: Pass or fail the job
+        run: |
+            if ["$RESULTS_LENGTH" != 0]; then
+               echo "Job Failed"
+               exit 1
+            else
+               echo "Papu Pass Ho Gaya"
+               
       - name: Send notification on Slack using Webhooks
         uses: slackapi/slack-github-action@v1.24.0
         if: always()
